force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Back_Office_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Back_Office_Configuration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Back-Office Configuration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_code_number__c.field-meta.xml
<CustomField>
    <fullName>Branch_code_number__c</fullName>
    <description>for US accounts</description>
    <label>Branch code number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Buyback__c.field-meta.xml
<CustomField>
    <fullName>Buyback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Buyback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Buyback_limitation__c.field-meta.xml
<CustomField>
    <fullName>Buyback_limitation__c</fullName>
    <label>Buyback limitation</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Commission</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_id_num__c.field-meta.xml
<CustomField>
    <fullName>Company_id_num__c</fullName>
    <label>Company id. num.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Klarna__c.field-meta.xml
<CustomField>
    <fullName>Klarna__c</fullName>
    <label>Klarna</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_Fees__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Fees__c</fullName>
    <label>Monthly Fees</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reason_for_last_Sales_limitation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_last_Sales_limitation__c</fullName>
    <label>Reason for last Sales limitation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_for_limitation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_limitation__c.field-meta.xml
<CustomField>
    <fullName>Sales_limitation__c</fullName>
    <label>Sales limitation</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Split_Payment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Split_Payment_Stage__c</fullName>
    <label>Oney FR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Paypal_Score_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Story__c.field-meta.xml
<CustomField>
    <fullName>Story__c</fullName>
    <label>Story</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>backwatch</fullName>
                <label>BackWatch</label>
            </value>
            <value>
                <fullName>nmo</fullName>
                <label>N.M.O.</label>
            </value>
            <value>
                <fullName>partnership</fullName>
                <label>Strategic Partnership</label>
            </value>
            <value>
                <fullName>brand_or_retailer</fullName>
                <label>Brand &amp; Retailer</label>
            </value>
            <value>
                <fullName>hand_free</fullName>
                <label>Selfcare</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_BO_International_Onboarding__c.field-meta.xml
<CustomField>
    <fullName>TECH_BO_International_Onboarding__c</fullName>
    <formula>IF(

AND(
RecordType.DeveloperName = &apos;E_U&apos;,
ISPICKVAL(Stage__c , &quot;Run&quot;),
Exit_granted__c =FALSE,
NOT(ISPICKVAL( Country__c ,&quot;United Kingdom&quot;))),

TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH BO International Onboarding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trading_Name__c.field-meta.xml
<CustomField>
    <fullName>Trading_Name__c</fullName>
    <label>Legal Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>Company Tax Number (VAT)</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/E_U.recordType-meta.xml
<RecordType>
    <fullName>E_U</fullName>
    <active>true</active>
    <label>E.U.</label>
</RecordType>

force-app/main/default/objects/EU_Back_Office_Settings__c/EU_Back_Office_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is where the Back-Office settings EU are defined (Url., Username, Password).</description>
    <label>E.U. Back-Office Settings</label>
</CustomObject>

force-app/main/default/objects/EU_Back_Office_Settings__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>password used to connect with backoffice</description>
    <label>password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EU_Back_Office_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>username used to connect to the back office</description>
    <label>username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/Targeted_Country__c.object-meta.xml
<CustomObject>
    <description>This Object is a Junction Object between Account and Country.</description>
    <label>Targeted Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Targeted Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeted_Country__c/fields/Back_Care__c.field-meta.xml
<CustomField>
    <fullName>Back_Care__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Back Care</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Buyback_BO_Status__c.field-meta.xml
<CustomField>
    <fullName>Buyback_BO_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Buyback BO Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availables_countries_to_sell_into</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Online_Status__c.field-meta.xml
<CustomField>
    <fullName>Online_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeted_Country_Online_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Shipping_From__c.field-meta.xml
<CustomField>
    <fullName>Shipping_From__c</fullName>
    <description>Field used to indicate where from the merchant is shipping to the selected Targeted Country.</description>
    <label>Shipping From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/recordTypes/E_U.recordType-meta.xml
<RecordType>
    <fullName>E_U</fullName>
    <active>true</active>
    <description>Targeted Country For U.E.</description>
    <label>E.U. TC</label>
</RecordType>

force-app/main/default/objects/US_Back_Office_Settings__c/US_Back_Office_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is where the Back-Office settings US are defined (Url., Username, Password).</description>
    <label>U.S. Back-Office Settings</label>
</CustomObject>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/Backoffice_URL__c.field-meta.xml
<CustomField>
    <fullName>Backoffice_URL__c</fullName>
    <description>Root U.R.L. of the Back-Office REST A.P.I.&apos;s end-point</description>
    <label>BackOffice U.R.L.</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>username used to connect to the back office</description>
    <label>username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Availables_countries_to_sell_into.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <masterLabel>Availables countries to sell into</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Paypal_Score_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
        <isActive>false</isActive>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
        <isActive>false</isActive>
        <label>Negotiation</label>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
        <isActive>false</isActive>
        <label>Refused</label>
    </customValue>
    <masterLabel>Paypal Score Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Reason_for_limitation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SELLER_LIFE_CYCLE_LAUNCHING_PHASE</fullName>
        <label>Seller life cycle launching phase</label>
    </customValue>
    <customValue>
        <fullName>SELLER_LIFE_CYCLE_SEATBELT</fullName>
        <label>Seller life cycle seatbelt</label>
    </customValue>
    <customValue>
        <fullName>SELLER_LIFE_CYCLE_EXIT</fullName>
        <label>Seller life cycle exit</label>
    </customValue>
    <customValue>
        <fullName>QUALITY_MONITORING_PERIOD</fullName>
        <label>Quality Monitoring Period</label>
    </customValue>
    <customValue>
        <fullName>QUALITY_LEGAL_AND_SAFETY_ISSUE</fullName>
        <label>Quality Legal and Safety Issue</label>
    </customValue>
    <customValue>
        <fullName>QUALITY_RESTRICTED_CATEGORY</fullName>
        <label>Quality Restricted Category</label>
    </customValue>
    <customValue>
        <fullName>QUALITY_OTHER</fullName>
        <label>Quality Other</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS_REASON_PRODUCT_MIX_OPTIMIZATION</fullName>
        <label>Business Reason Product Mix Optimization</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS_REASON_OTHER</fullName>
        <label>Business Reason Other</label>
    </customValue>
    <customValue>
        <fullName>No limitation</fullName>
    </customValue>
    <customValue>
        <fullName>T&amp;Cs not signed</fullName>
    </customValue>
    <masterLabel>Reason for limitation</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Targeted_Country_Online_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Candidate</fullName>
        <default>true</default>
        <label>Candidate</label>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>Ready</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Targeted Country Online Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DCE_BackOfficeCallouts.cls
/********************************************************************************
    * Création : Rémy VULTAGGIO - 03/05/2019
    * Modif :
    * Tests : DCE_TriggersTest
    *
    * Allows to make every RESP API callouts to the Back-Office.
    *
    *   Purpose : Group together in the same class all the REST API calls that can
    * be made to the Back-Office.
********************************************************************************/

public class DCE_BackOfficeCallouts {
    private static final String CLASS_NAME = 'DCE_BackOfficeCallouts'; //should be updated if the class name is changed

    /**
        * Private variable
        **/
    private static Map<String, String> MAP_COUNTRIES_CODES = new Map<String, String>{
        'France' => 'fr_fr',
        'Belgium' => 'fr_be',
        'Spain' => 'es_es',
        'Italy' => 'it_it',
        'Germany' => 'de_de',
        'United States' => 'en_us',
        'United Kingdom' => 'en_gb',
        'Austria' => 'de_at',
        'Netherlands' => 'nl_nl',
        'Finland' => 'fi_fi',
        'Portugal' => 'pt_pt',
        'Ireland' => 'en_ie',
        'Greece' => 'el_gr',
        'Slovakia' => 'sk_sk',
        'Sweden' => 'sv_se'
    };

    private static Map<String, String> MAP_FIELDS_SF_BO = new Map<String, String>{
        'trading_name__c' => 'pseudo',
        'vat_number__c' => 'vat_number',
        'company_id_num__c' => 'siret_number',
        'story__c' => 'business_level',
        'split_payment_stage__c' => 'accepts_payment_in_installments',
        'klarna__c' => 'accepts_payment_with_klarna',
        'bizdev__c' => 'account_manager_email',
        'commission__c' => 'fee',
        'back_office_configuration__c' => 'is_configured',
        'iban__c' => 'iban',
        'bic__c' => 'bic',
        'branch_code_number__c' => 'branch_code',
        'account_number__c' => 'account_number', 
        'monthly_fees__c' => 'monthly_fee',
        'back_care__c' => 'backcare',
        'online_status__c' => 'online',
        'billingstreet' => 'street',
        'billingcity' => 'city',
        'billingpostalcode' => 'postal_code',
        'billingcountrycode' => 'country',
        'billingstatecode' => 'state_or_province',
        'mobilephone' => 'phone',
        'buyback__c' => 'sourcing',
        'buyback_limitation__c' => 'sourcing_threshold',
        'buyback_bo_status__c' => 'buyback_enabled',
        'tech_bo_international_onboarding__c' => 'can_open_more_markets',
        'country__c' => 'country_of_origin',
        'shipping_from__c' => 'expedition_country',
        'sales_limitation__c' => 'sales_threshold',
        'reason_for_last_sales_limitation__c' => 'reason'
    };

    /**
        * Public Callouts Methods
        **/
    @future(callout = true)
    public static void makeCallout(String jsonRequestBody, String marketplace) {
        makeImmediateCallout(jsonRequestBody, marketplace);
    }

    /**
        * Private Methods
        **/
    private static void makeImmediateCallout (String jsonRequestBody, String marketplace) {
        String url, username, password;

        if ( marketplace == 'EU' ){
            EU_Back_Office_Settings__c settings = EU_Back_Office_Settings__c.getInstance();
            url = settings.backoffice_url__c;
            username = settings.username__c;
            password = settings.password__c;

        } else if (marketplace == 'US') {
            US_Back_Office_Settings__c settings = US_Back_Office_Settings__c.getInstance();
            url = settings.backoffice_url__c;
            username = settings.username__c;
            password = settings.password__c;

        } else {
            return;
        }

        String token = EncodingUtil.base64Encode(Blob.valueof(username + ':' + password));

        HttpRequest request = new HttpRequest();
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept', 'application/json');
        request.setHeader('Authorization', 'Basic ' + token);

        request.setEndpoint(url);
        request.setMethod('PUT');
        request.setBody(jsonRequestBody);

        Http http = new Http();
        HttpResponse response;
        API_Log__e logEvent;
        try {
            response = http.send(request);
        
            LogService.log(response.getStatusCode() != 200 ? LogService.LOG_TYPE.ERROR : LogService.LOG_TYPE.SUCCESS, LogService.PROCESS.BACK_OFFICE_CALLOUT, request, response, 'Callout response', CLASS_NAME);
        } catch (CalloutException e) {
            LogService.log(LogService.LOG_TYPE.ERROR, LogService.PROCESS.BACK_OFFICE_CALLOUT, request, response, e.getMessage(), CLASS_NAME);
        } catch (Exception e) {
            LogService.log(LogService.LOG_TYPE.ERROR, LogService.PROCESS.BACK_OFFICE_CALLOUT, request, response, e.getMessage(), CLASS_NAME);
        }
    }

    /**
        * This method is meant to sync every creation or modification with the Back-Office.
        **/
    public static void doBackOfficeSync( String sObjectAPIName, String operationType, Map < ID, SObject > oldSObjectsMap, List < SObject > newSObjectsList ) {
        Boolean isUpdate = ( 'Update'.equals( operationType ) );

        Map < String, Schema.SObjectField > sObjectFieldsMap = Schema.getGlobalDescribe().get( sObjectAPIName ).getDescribe().fields.getMap();

        List < Map < String, Object > > merchantsToUpdateEU = new List < Map < String, Object > >();
        List < Map < String, Object > > merchantsToUpdateUS = new List < Map < String, Object > >();

        Set<Id> recordIds = new Set<Id>();

        for ( SObjectWrapper wrapper : retreiveBackOfficeInfo(newSObjectsList) ) {
            SObject newSObjectTmp = wrapper.obj;
            recordIds.add(newSObjectTmp.Id);
            SObject oldSObjectTmp = ( isUpdate
                                        ? oldSObjectsMap.get( newSObjectTmp.Id )
                                        : null );

            if ( doPreChecks( oldSObjectTmp, newSObjectTmp ) ) {
                Map < String, Object > merchantInfo = new Map < String, Object >();

                for ( String fieldAPIName : sObjectFieldsMap.keySet() ) {
                    if ( ( isUpdate
                            && newSObjectTmp.get( fieldAPIName ) != oldSObjectTmp.get( fieldAPIName ) )
                            || ( !isUpdate
                                && newSObjectTmp.get( fieldAPIName ) != null ) ) {
                                    doCompleteMerchantInfo(merchantInfo, sObjectAPIName, wrapper, fieldAPIName);
                    }
                }

                if (!merchantInfo.isEmpty() ){
                    merchantInfo.put('salesforce_id', wrapper.accountId);
                    merchantInfo.put('id', wrapper.backOfficeId);
                    
                    if (wrapper.marketplace == MARKET_PLACE.EU){
                        merchantsToUpdateEU.add(merchantInfo);
                    } else if (wrapper.marketplace == MARKET_PLACE.US) {
                        merchantsToUpdateUS.add(merchantInfo);
                    }
                    
                }

            }
        }

        if(merchantsToUpdateEU.isEmpty() == false || merchantsToUpdateUS.isEmpty() == false){
            // replacing bizdev id by its email
            Map<String, List<Decimal>> backOfficeIdsByBizDevId = new Map<String, List<Decimal>>();
            for(Map < String, Object > merchantInfo : merchantsToUpdateEU){
                if(merchantInfo.containsKey('account_manager_email')){
                    String bizdevId = (String)merchantInfo.get('account_manager_email');
                    if(backOfficeIdsByBizDevId.containsKey(bizdevId) == false){
                        backOfficeIdsByBizDevId.put(bizdevId, new List<Decimal>());
                    }

                    backOfficeIdsByBizDevId.get(bizdevId).add((Decimal)merchantInfo.get('id'));
                }
            }
            for(Map < String, Object > merchantInfo : merchantsToUpdateUS){
                if(merchantInfo.containsKey('account_manager_email')){
                    String bizdevId = (String)merchantInfo.get('account_manager_email');
                    if(backOfficeIdsByBizDevId.containsKey(bizdevId) == false){
                        backOfficeIdsByBizDevId.put(bizdevId, new List<Decimal>());
                    }

                    backOfficeIdsByBizDevId.get(bizdevId).add((Decimal)merchantInfo.get('id'));
                }
            }
            Map<Id, User> userBydId = new Map<Id, User>([SELECT Email FROM User WHERE Id IN :backOfficeIdsByBizDevId.keySet()]);
            for(Map < String, Object > merchantInfo : merchantsToUpdateEU){
                if(merchantInfo.containsKey('account_manager_email')){
                    String currentUserId = (String)merchantInfo.get('account_manager_email');
                    merchantInfo.put('account_manager_email', userBydId.get(currentUserId).Email);
                }
            }
            for(Map < String, Object > merchantInfo : merchantsToUpdateUS){
                if(merchantInfo.containsKey('account_manager_email')){
                    String currentUserId = (String)merchantInfo.get('account_manager_email');
                    merchantInfo.put('account_manager_email', userBydId.get(currentUserId).Email);
                }
            }

            LogService.log(LogService.LOG_TYPE.INFO, LogService.PROCESS.BACK_OFFICE_CALLOUT, recordIds, 'Starting callout', CLASS_NAME);
            
            try{
                if (! merchantsToUpdateEU.isEmpty()) {
                    DCE_BackOfficeCallouts.makeCallout ( JSON.serialize(merchantsToUpdateEU), 'EU');
                }
                if (! merchantsToUpdateUS.isEmpty()) {
                    DCE_BackOfficeCallouts.makeCallout ( JSON.serialize(merchantsToUpdateUS), 'US');
                }
            }
            catch(JSONException e){
                LogService.log(LogService.LOG_TYPE.ERROR, LogService.PROCESS.BACK_OFFICE_CALLOUT, recordIds, e.getMessage(), CLASS_NAME);
            }
        }
    }

    /**
        * This method is meant to determine whether a Record must be processed or not.
        **/
    private static Boolean doPreChecks ( SObject oldSObject, SObject newSObject ) {
        Boolean result = false;

        switch on newSObject {
            when Contact c {
                result = ( c.Merchant_ID__c != NULL  );
            }
            when Account a {
                result = true;
            }
            when Targeted_Country__c tc {
                result = true;
            }
            when else {
                // NOTHING TO DO
            }
        }

        return result;
    }

    /**
        * This method is meant to help complete the REST HTTP query body in JSON format.
        **/
    private static void doCompleteMerchantInfo( Map < String, Object > merchantInfo, String sObjectAPIName, SObjectWrapper wrapper, String fieldAPIName) {
        Object newValue = wrapper.obj.get( fieldAPIName );

        switch on sObjectAPIName {
            when 'Account' {
                switch on fieldAPIName {
                    when 'trading_name__c', 'vat_number__c', 'company_id_num__c', 'story__c', 'country__c'  {
                        newValue = (newValue != null) ? (String) newValue : '';
                        merchantInfo.put(MAP_FIELDS_SF_BO.get(fieldAPIName), newValue);
                    }

                    when 'commission__c' {
                        newValue = (Decimal) newValue;
                        if (newValue != null)
                            merchantInfo.put(MAP_FIELDS_SF_BO.get(fieldAPIName), newValue);
                    }

                    when 'monthly_fees__c' {
                        newValue = (newValue != null) ? (Decimal) newValue : 0;
                        merchantInfo.put(MAP_FIELDS_SF_BO.get(fieldAPIName), newValue);
                    }

                    when 'split_payment_stage__c', 'klarna__c' {
                        String fieldName = MAP_FIELDS_SF_BO.get(fieldAPIName);
                        newValue = ((String) newValue) == 'Live' ? true : false ;
                        merchantInfo.put(fieldName, newValue);

                    }

                    when 'bizdev__c' {
                        Id user_id = (Id) newValue;
                        if (user_id != null){
                            merchantInfo.put(MAP_FIELDS_SF_BO.get(fieldAPIName), user_id);
                        }
                    }

                    when 'billingstreet', 'billingcity', 'billingpostalcode', 'billingcountrycode', 'billingstatecode' {
                        String fieldBoName = MAP_FIELDS_SF_BO.get(fieldAPIName);
                        newValue = (newValue != null) ? (String) newValue : '';

                        if (fieldAPIName == 'billingcountrycode' && newValue == '') // backoffice does not accept null value
                            return;

                        if (!merchantInfo.containsKey('address'))
                            merchantInfo.put('address', new Map < String, Object >());

                        ((Map < String, Object >) merchantInfo.get('address')).put(fieldBoName, newValue);
                    }

                    when 'iban__c', 'bic__c', 'branch_code_number__c', 'account_number__c' {
                        String fieldBoName = MAP_FIELDS_SF_BO.get(fieldAPIName);
                        newValue = (newValue != null) ? (String) newValue : '';

                        if (!merchantInfo.containsKey('wallet'))
                                merchantInfo.put('wallet', new Map < String, Object >());

                        ((Map < String, Object >) merchantInfo.get('wallet')).put(fieldBoName, newValue);
                    }

                    when 'back_office_configuration__c', 'buyback__c', 'tech_bo_international_onboarding__c' {
                        newValue = (Boolean) newValue;
                        merchantInfo.put(MAP_FIELDS_SF_BO.get(fieldAPIName), newValue);
                    }
                    
                    when 'buyback_limitation__c' {
                        newValue = (newValue != null) ? ((Decimal) newValue).intValue() : 0;
                        merchantInfo.put(MAP_FIELDS_SF_BO.get(fieldAPIName), newValue);
                    }
                    
                    when 'sales_limitation__c', 'reason_for_last_sales_limitation__c' {
                        if (!merchantInfo.containsKey('sales_limitation'))
                            merchantInfo.put('sales_limitation', new Map < String, Object >());
                        
                        String fieldBoName = MAP_FIELDS_SF_BO.get(fieldAPIName);
                        ((Map < String, Object >) merchantInfo.get('sales_limitation')).put(fieldBoName, newValue);
                    }
                    
                    
                }
            }
            when 'Contact' {
                switch on fieldAPIName {
                    when 'mobilephone'{
                        String fieldBoName = MAP_FIELDS_SF_BO.get(fieldAPIName);
                        newValue = (newValue != null) ? (String) newValue : '';

                        if (!merchantInfo.containsKey('address'))
                            merchantInfo.put('address', new Map < String, Object >());

                        ((Map < String, Object >) merchantInfo.get('address')).put(fieldBoName, newValue);
                    }
                }
            }
            when 'Targeted_Country__c' {
                if (wrapper.countryCode == null)
                    return;

                String fieldBoName = MAP_FIELDS_SF_BO.get(fieldAPIName) + '_' + wrapper.countryCode;
                switch on fieldAPIName {
                    when 'online_status__c' {
                        newValue = ((String) newValue) == 'Live' ? true : false ;
                        merchantInfo.put(fieldBoName, newValue);
                    }

                    when 'back_care__c', 'buyback_bo_status__c' {
                        newValue = (Boolean) newValue;
                        merchantInfo.put(fieldBoName, newValue);
                    }
                    
                    when 'shipping_from__c' {
                        newValue = (String) newValue;
                        merchantInfo.put(fieldBoName, newValue);
                    }
                }
            }
        }
    }

    private static List<SObjectWrapper> retreiveBackOfficeInfo( List<SObject> newSObjectList ){
        // matching each record to its merchant account
        Map<Id, List<SObject>> sobjectsByAccountId = new Map<Id, List<SObject>>();
        for(SObject obj : newSObjectList){
            switch on obj {
                when Contact contact {
                    if(sobjectsByAccountId.containsKey(contact.AccountId) == false){
                        sobjectsByAccountId.put(contact.AccountId, new List<SObject>());
                    }
                    sobjectsByAccountId.get(contact.AccountId).add(contact);
                }

                when Account account {
                    if(sobjectsByAccountId.containsKey(account.Id) == false){
                        sobjectsByAccountId.put(account.Id, new List<SObject>());
                    }
                    sobjectsByAccountId.get(account.Id).add(account);
                }

                when Targeted_Country__c targetCountry {
                    if(sobjectsByAccountId.containsKey(targetCountry.Merchant__c) == false){
                        sobjectsByAccountId.put(targetCountry.Merchant__c, new List<SObject>());
                    }
                    sobjectsByAccountId.get(targetCountry.Merchant__c).add(targetCountry);
                }
            }
        }

        List<SObjectWrapper> wrappers = new List<SObjectWrapper>();
        for(Account acc : [SELECT Back_Office_PK__c, RecordType.DeveloperName FROM Account WHERE Id IN :sobjectsByAccountId.keySet() AND Back_Office_PK__c != null]){
            for(SObject obj : sobjectsByAccountId.get(acc.Id)){
                SObjectWrapper wrapper = new SObjectWrapper(obj);

                wrapper.accountId = acc.Id;
                wrapper.backofficeId = acc.Back_Office_PK__c;
                if(obj.getSObjectType() == Targeted_Country__c.sObjectType){
                    wrapper.countryCode = MAP_COUNTRIES_CODES.get(((Targeted_Country__c)obj).Country__c);
                }
                wrapper.marketPlace = (acc.RecordType.DeveloperName == 'E_U' ? MARKET_PLACE.EU: MARKET_PLACE.US);

                wrappers.add(wrapper);
            }
        }

        return wrappers;
    }

    private Enum MARKET_PLACE{
        EU,
        US
    }

    private class SObjectWrapper{
        public Decimal backofficeId;
        public Id accountId;
        public MARKET_PLACE marketPlace;
        public String countryCode;
        public SObject obj;

        public SObjectWrapper(Sobject obj){
            this.obj = obj;
        }
    }
}