force-app/main/default/objects/Account/fields/Back_Office_PK__c.field-meta.xml
<CustomField>
    <fullName>Back_Office_PK__c</fullName>
    <description>Primary key from the equivalent record in the Back-Office database.</description>
    <externalId>true</externalId>
    <label>P.K.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fatness__c.field-meta.xml
<CustomField>
    <fullName>Fatness__c</fullName>
    <inlineHelpText>This field is mandatory to move from Identification to first contact!</inlineHelpText>
    <label>Fatness</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inputted_from__c.field-meta.xml
<CustomField>
    <fullName>Inputted_from__c</fullName>
    <description>Where the data were originally inputted.</description>
    <label>Inputted from</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Back-Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <inlineHelpText>This field is mandatory to move from Identification to first contact!</inlineHelpText>
    <label>Type of company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_company_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <businessOwnerUser>arthur.veron@backmarket.com</businessOwnerUser>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <inlineHelpText>This field is mandatory to move from Identification to first contact!</inlineHelpText>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>fr-fr</fullName>
                <label>FR</label>
            </value>
            <value>
                <fullName>es-es</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>it-it</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>fr-be</fullName>
                <label>BE</label>
            </value>
            <value>
                <fullName>de-de</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>en-eu</fullName>
                <label>EN</label>
            </value>
            <value>
                <fullName>en-us</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>en-gb</fullName>
                <label>GB</label>
            </value>
            <value>
                <fullName>de-at</fullName>
                <label>AT</label>
            </value>
            <value>
                <fullName>nl-nl</fullName>
                <label>NL</label>
            </value>
            <value>
                <fullName>fi-fi</fullName>
                <label>FI</label>
            </value>
            <value>
                <fullName>jp-jp</fullName>
                <label>JP</label>
            </value>
            <value>
                <fullName>pt-pt</fullName>
                <label>PT</label>
            </value>
            <value>
                <fullName>en-ie</fullName>
                <label>IE</label>
            </value>
            <value>
                <fullName>el-gr</fullName>
                <label>GR</label>
            </value>
            <value>
                <fullName>sk-sk</fullName>
                <label>SK</label>
            </value>
            <value>
                <fullName>sv-se</fullName>
                <label>SE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EU_Back_Office_Settings__c/EU_Back_Office_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is where the Back-Office settings EU are defined (Url., Username, Password).</description>
    <label>E.U. Back-Office Settings</label>
</CustomObject>

force-app/main/default/objects/EU_Back_Office_Settings__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>password used to connect with backoffice</description>
    <label>password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EU_Back_Office_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>username used to connect to the back office</description>
    <label>username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/US_Back_Office_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is where the Back-Office settings US are defined (Url., Username, Password).</description>
    <label>U.S. Back-Office Settings</label>
</CustomObject>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/Backoffice_URL__c.field-meta.xml
<CustomField>
    <fullName>Backoffice_URL__c</fullName>
    <description>Root U.R.L. of the Back-Office REST A.P.I.&apos;s end-point</description>
    <label>BackOffice U.R.L.</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>password used to connect to the back office</description>
    <label>password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>username used to connect to the back office</description>
    <label>username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Identification</fullName>
        <default>true</default>
        <label>Identification</label>
    </customValue>
    <customValue>
        <fullName>Not relevant</fullName>
    </customValue>
    <customValue>
        <fullName>First-contact</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Future partnership</fullName>
    </customValue>
    <customValue>
        <fullName>N.M.O.</fullName>
        <label>Launching Phase</label>
    </customValue>
    <customValue>
        <fullName>Run</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Central America</fullName>
    </customValue>
    <customValue>
        <fullName>Central Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Eastern Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Eastern Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Latin America and the Caribbean</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Northern America</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>South-eastern Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Southern Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Sub-Saharan Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Western Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Western Europe</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type_of_company_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Social Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Brand</fullName>
    </customValue>
    <customValue>
        <fullName>Buyback</fullName>
        <label>Buy&amp;Sell Store</label>
    </customValue>
    <customValue>
        <fullName>Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Company Group</fullName>
    </customValue>
    <customValue>
        <fullName>Large Corporation</fullName>
    </customValue>
    <customValue>
        <fullName>Medium Company</fullName>
    </customValue>
    <customValue>
        <fullName>Public Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Small Company</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Telecommunications</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Platform E-commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>IT Asset Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Micro-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Online Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Recycler</fullName>
    </customValue>
    <customValue>
        <fullName>Refurbisher</fullName>
    </customValue>
    <customValue>
        <fullName>Repairer</fullName>
    </customValue>
    <customValue>
        <fullName>Reverse Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Trader</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesaler</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic Partnership</fullName>
        <isActive>false</isActive>
        <label>Strategic Partnership</label>
    </customValue>
    <customValue>
        <fullName>Backwatch</fullName>
        <isActive>false</isActive>
        <label>Backwatch</label>
    </customValue>
    <masterLabel>Type of company - Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DCE_Test_Trigger_Contact_Account.cls
/**********************************************
* CREATION : YBD 10/07/2019
* MODIFS :
* Permet de tester :    - Le trigger  DCE_AccountTrigger
*                       - Le trigger  DCE_ContactTrigger
* ******************************************/
@isTest
public class DCE_Test_Trigger_Contact_Account {

    @TestSetup
    static void makeData(){
        new TestFactory().setCustomSettings();

        insert new EU_Back_Office_Settings__c(
            backoffice_url__c = 'test.backmarket.com',
            username__c = 'test_username',
            password__c = 'test_password'
        );
        insert new US_Back_Office_Settings__c(
            backoffice_url__c = 'testus.backmarket.com',
            username__c = 'test_username',
            password__c = 'test_password'
        );
    }
    
    @isTest
    public static void handleAccountTrigger_Test(){
        Account acc = new Account(Name='marchand test apex',Stage__c = 'Identification', BillingCountry = 'France', Country__c = 'France',Region__c ='Western Europe');
        insert acc;
        
        Account accResult = [SELECT 
                             Id,
                             Stage__c,
                             Type
                             FROM Account WHERE Id = :acc.Id
                            ];
                
        Id currentUser = UserInfo.getUserId();
        accResult.Zone__c = 'fr-fr';
        accResult.AccountSource = 'Entrant Lead';
        accResult.Profile__c = 'Classic';
        accResult.BizDev__c = currentUser;
        accResult.Fatness__c = 2;
        accResult.Stage__c = 'First-contact';
        update accResult;
    }
    
    @isTest
    public static void handleContactTrigger_Test(){
        
        Account acc = new Account(Name='marchand test apex',Stage__c = 'Identification',Back_Office_PK__c=99999,Inputted_from__c='Back-Office', BillingCountry = 'France', Country__c = 'France',Region__c ='Western Europe');
        insert acc;
       
        Contact ctc = new Contact(Lastname='contact test apex',Email='test@test.com',AccountId=acc.Id);
        insert ctc;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DCE_CalloutsMock());
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'PUT';  
        RestContext.request = req;
        RestContext.response = res;
        Test.stopTest();
        
    }

}