force-app/main/default/objects/Account/fields/Back_Office_PK__c.field-meta.xml
<CustomField>
    <fullName>Back_Office_PK__c</fullName>
    <description>Primary key from the equivalent record in the Back-Office database.</description>
    <externalId>true</externalId>
    <label>P.K.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Buyback_limitation__c.field-meta.xml
<CustomField>
    <fullName>Buyback_limitation__c</fullName>
    <label>Buyback limitation</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BuyBack_Stage__c.field-meta.xml
<CustomField>
    <fullName>BuyBack_Stage__c</fullName>
    <label>BuyBack Stage_old</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Commission</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_id_num__c.field-meta.xml
<CustomField>
    <fullName>Company_id_num__c</fullName>
    <label>Company id. num.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inputted_from__c.field-meta.xml
<CustomField>
    <fullName>Inputted_from__c</fullName>
    <description>Where the data were originally inputted.</description>
    <label>Inputted from</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Back-Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Klarna__c.field-meta.xml
<CustomField>
    <fullName>Klarna__c</fullName>
    <label>Klarna</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_Fees__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Fees__c</fullName>
    <label>Monthly Fees</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_limitation__c.field-meta.xml
<CustomField>
    <fullName>Sales_limitation__c</fullName>
    <label>Sales limitation</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Story__c.field-meta.xml
<CustomField>
    <fullName>Story__c</fullName>
    <label>Story</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>backwatch</fullName>
                <label>BackWatch</label>
            </value>
            <value>
                <fullName>nmo</fullName>
                <label>N.M.O.</label>
            </value>
            <value>
                <fullName>partnership</fullName>
                <label>Strategic Partnership</label>
            </value>
            <value>
                <fullName>brand_or_retailer</fullName>
                <label>Brand &amp; Retailer</label>
            </value>
            <value>
                <fullName>hand_free</fullName>
                <label>Selfcare</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trading_Name__c.field-meta.xml
<CustomField>
    <fullName>Trading_Name__c</fullName>
    <label>Legal Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Merchant ID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EU_Back_Office_Settings__c/EU_Back_Office_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is where the Back-Office settings EU are defined (Url., Username, Password).</description>
    <label>E.U. Back-Office Settings</label>
</CustomObject>

force-app/main/default/objects/EU_Back_Office_Settings__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>password used to connect with backoffice</description>
    <label>password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EU_Back_Office_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>username used to connect to the back office</description>
    <label>username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Limitation__c/Sales_Limitation__c.object-meta.xml
<CustomObject>
    <description>Allow to create a limitation on the number of sales allowed for a Merchant and optionnaly a Targeted Country</description>
    <label>Sales Limitation</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Sales Limitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Limitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Limitation__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Limitations</relationshipLabel>
    <relationshipName>Sales_Limitations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Limitation__c/fields/Targeted_Country__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Targeted Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Targeted_Country__c.Merchant__c</field>
            <operation>equals</operation>
            <valueField>$Source.Merchant__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Targeted_Country__c</referenceTo>
    <relationshipLabel>Sales Limitations</relationshipLabel>
    <relationshipName>Sales_Limitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/Targeted_Country__c.object-meta.xml
<CustomObject>
    <description>This Object is a Junction Object between Account and Country.</description>
    <label>Targeted Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Targeted Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeted_Country__c/fields/Back_Care__c.field-meta.xml
<CustomField>
    <fullName>Back_Care__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Back Care</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availables_countries_to_sell_into</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Targeted Countries</relationshipLabel>
    <relationshipName>Targeted_Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Online_Status__c.field-meta.xml
<CustomField>
    <fullName>Online_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeted_Country_Online_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Shipping_From__c.field-meta.xml
<CustomField>
    <fullName>Shipping_From__c</fullName>
    <description>Field used to indicate where from the merchant is shipping to the selected Targeted Country.</description>
    <label>Shipping From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/US_Back_Office_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is where the Back-Office settings US are defined (Url., Username, Password).</description>
    <label>U.S. Back-Office Settings</label>
</CustomObject>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/Backoffice_URL__c.field-meta.xml
<CustomField>
    <fullName>Backoffice_URL__c</fullName>
    <description>Root U.R.L. of the Back-Office REST A.P.I.&apos;s end-point</description>
    <label>BackOffice U.R.L.</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>password used to connect to the back office</description>
    <label>password</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/US_Back_Office_Settings__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>username used to connect to the back office</description>
    <label>username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Availables_countries_to_sell_into.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <masterLabel>Availables countries to sell into</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Targeted_Country_Online_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Candidate</fullName>
        <default>true</default>
        <label>Candidate</label>
    </customValue>
    <customValue>
        <fullName>Selected</fullName>
    </customValue>
    <customValue>
        <fullName>Ready</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Targeted Country Online Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DCE_TriggersTest.cls
/********************************************************************************
 * Création : Rémy VULTAGGIO - 07/05/2019
 * Modif :
 *
 * Class allowing to test API REST callouts to the Back-Office.
 *
 * Purpose :
 * Cover at least 75% of the code from the classes DCE_<???>Trigger[Handler].
 ********************************************************************************/
@IsTest
private without sharing class DCE_TriggersTest {
    /**
     * Init data methods
     **/
    @testSetup
    private static void init() {
        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.needTest = false;

        Test.setMock(HttpCalloutMock.class, calloutsMock);

        TestFactory factory = new TestFactory();
        factory.setCustomSettings();

        Account acc = factory.getAccountFR('Merchant');
        acc.Back_Office_PK__c = 99999;
        acc.inputted_from__c = 'Back-Office';
        insert acc;

        Contact con = factory.getContact(acc.Id, 'Test', 'Test');
        con.Merchant_ID__c = '99999';
        insert con;

        insert new Targeted_Country__c(
            Merchant__c = acc.Id,
            Country__c='France',
            Online_Status__c = 'Selected',
            back_care__c = true
        );

        insert new EU_Back_Office_Settings__c(
            backoffice_url__c = 'test.backmarket.com',
            username__c = 'test_username',
            password__c = 'test_password'
        );
        insert new US_Back_Office_Settings__c(
            backoffice_url__c = 'testus.backmarket.com',
            username__c = 'test_username',
            password__c = 'test_password'
        );
    }

    /**
     * Tests methods
     **/
    @IsTest
    private static void testdoBackOfficeSyncAccount(){
        String accountName = 'Merchant';
        Set<String> accountfieldNames = Account.sObjectType.getDescribe().fields.getMap().keySet();

        Account account = Database.query('select ' + string.join((Iterable<String>)accountfieldNames, ',') + ' from Account where Name =:accountName');
        Account newAccount = Database.query('select ' + string.join((Iterable<String>)accountfieldNames, ',') + ' from Account where Name =:accountName');

        newAccount.trading_name__c = 'recommerce';
        newAccount.company_id_num__c = 'company';
        newAccount.story__c = '2';
        newAccount.commission__c = 8;
        newAccount.monthly_fees__c = 11;
        newAccount.buyback_stage__c = 'Live';
        newAccount.iban__c = 'iban-xxxx';
        newAccount.bic__c = 'bic-xxxx';
        newAccount.billingstreet = 'rue street';
        newAccount.klarna__c = 'Offline';
        newAccount.buyback_limitation__c = 10;
        newAccount.sales_limitation__c = 10;

        Map<ID, SObject> oldSObjectsMap = new Map<ID, SObject>{
            account.Id => account
        };

        List <Account> newSObjectsList = new List <Account>();
        newSObjectsList.add(newAccount);

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_MERCHANT_UPDATE;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        Test.startTest();

        DCE_BackOfficeCallouts.doBackOfficeSync('Account', 'Update', oldSObjectsMap, newSObjectsList);

        Test.stopTest();
    }

    @IsTest
    private static void testdoBackOfficeSyncAccountInsert(){
        Account newAccount = new TestFactory().getAccountUS('MerchantUS');
        newAccount.Back_Office_PK__c = 99998;
        newAccount.inputted_from__c = 'Back-Office';

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_MERCHANT_INSERT;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        
        Test.startTest();
        insert newAccount;
        Test.stopTest();
    }

    @IsTest
    private static void testdoBackOfficeSyncAccountInsertError(){
        Account newAccount = new TestFactory().getAccountUS('MerchantUS');
        newAccount.Back_Office_PK__c = 99998;
        newAccount.inputted_from__c = 'Back-Office';

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_ERROR;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        
        Test.startTest();
        insert newAccount;

        Test.getEventBus().deliver(); 
        Test.stopTest();

        System.assertEquals(1, LogService.results.size());
        for(Database.SaveResult result : LogService.results){
            System.assertEquals(true, result.isSuccess());
        }
    }

    @IsTest
    private static void testdoBackOfficeSyncAccountInsertException(){
        Account newAccount = new TestFactory().getAccountUS('MerchantUS');
        newAccount.Back_Office_PK__c = 99998;
        newAccount.inputted_from__c = 'Back-Office';

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_EXCEPTION;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        
        Test.startTest();
        insert newAccount;

        Test.getEventBus().deliver(); 
        Test.stopTest();

        System.assertEquals(1, LogService.results.size());
        for(Database.SaveResult result : LogService.results){
            System.assertEquals(true, result.isSuccess());
        }
    }


    @IsTest
    private static void testdoBackOfficeSyncAccountInsertHighVolume(){
        List<Account> accountsToInsert =  new List<Account>();
        for(Integer i = 0; i < TestFactory.LOAD_TEST_NUMBER; i++){
            Account newAccount = new TestFactory().getAccountUS('MerchantUS'+i);
            newAccount.Back_Office_PK__c = 99998;
            newAccount.inputted_from__c = 'Back-Office';

            accountsToInsert.add(newAccount);
        }

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_MERCHANT_INSERT;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        
        Test.startTest();
        insert accountsToInsert;
        Test.stopTest();
    }

    @IsTest
    private static void testdoBackOfficeSyncTargetCountry(){
        Set<String> targetCountryFieldNames = Targeted_Country__c.sObjectType.getDescribe().fields.getMap().keySet();

        Targeted_Country__c targetCountry = Database.query('select ' + string.join((Iterable<String>)targetCountryFieldNames, ',') + ' from Targeted_Country__c limit 1');
        Targeted_Country__c newTargetCountry = Database.query('select ' + string.join((Iterable<String>)targetCountryFieldNames, ',') + ' from Targeted_Country__c limit 1');

        System.debug('Country__c ' + targetCountry.Country__c);
        System.debug('Merchant__c ' + targetCountry.Merchant__c);
        System.debug('Online_Status__c ' + targetCountry.Online_Status__c);
        
        newTargetCountry.online_status__c = 'Live';
        newTargetCountry.shipping_from__c = 'France';
        newTargetCountry.back_care__c = false;

        Map<ID, SObject> oldSObjectsMap = new Map<ID, SObject>{
            targetCountry.Id => targetCountry
        };

        List <Targeted_Country__c> newSObjectsList = new List <Targeted_Country__c>();
        newSObjectsList.add(newTargetCountry);

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_TARGETEDCOUNTRY_UPDATE;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        Test.startTest();

        DCE_BackOfficeCallouts.doBackOfficeSync('Targeted_Country__c', 'Update', oldSObjectsMap, newSObjectsList);

        Test.stopTest();
    }

    @IsTest
    private static void testdoBackOfficeSyncContact(){
        Set<String> contactFieldNames = Contact.sObjectType.getDescribe().fields.getMap().keySet();

        Contact con = Database.query('select ' + string.join((Iterable<String>)contactFieldNames, ',') + ' from Contact limit 1');
        Contact newContact = Database.query('select ' + string.join((Iterable<String>)contactFieldNames, ',') + ' from Contact limit 1');
        
        newContact.MobilePhone = 'Test';

        Map<ID, SObject> oldSObjectsMap = new Map<ID, SObject>{
            con.Id => con
        };

        List <Contact> newSObjectsList = new List <Contact>();
        newSObjectsList.add(newContact);

        DCE_CalloutsMock calloutsMock = new DCE_CalloutsMock();
        calloutsMock.calloutType = DCE_CalloutsMock.DCE_CalloutType.BACKOFFICE_CONTACT_UPDATE;

        Test.setMock(HttpCalloutMock.class, calloutsMock);
        Test.startTest();

        DCE_BackOfficeCallouts.doBackOfficeSync('Contact', 'Update', oldSObjectsMap, newSObjectsList);

        Test.stopTest();
    }
}