force-app/main/default/objects/Account/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/BizDev_Buyback__c.field-meta.xml
<CustomField>
    <fullName>BizDev_Buyback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev Buyback</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager_Buyback__c.field-meta.xml
<CustomField>
    <fullName>Manager_Buyback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager - Buyback</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager_Sales__c.field-meta.xml
<CustomField>
    <fullName>Manager_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager - Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recipient_email_sales__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_sales__c</fullName>
    <label>Recipient email sales</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Alert</fullName>
            </value>
            <value>
                <fullName>Charter breach identified</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Not compliant</fullName>
            </value>
            <value>
                <fullName>Monitoring Period</fullName>
            </value>
            <value>
                <fullName>Last chance</fullName>
            </value>
            <value>
                <fullName>Doc validated pending MO result</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Doc missing</fullName>
            </value>
            <value>
                <fullName>Doc received and accepted</fullName>
            </value>
            <value>
                <fullName>Exit requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Merchant_BizDev__c.field-meta.xml
<CustomField>
    <fullName>Merchant_BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled by PB</inlineHelpText>
    <label>Merchant BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recipient_email_sales__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_sales__c</fullName>
    <label>Recipient email sales</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <color>#419249</color>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Refused</fullName>
                <color>#CC0000</color>
                <label>Refused</label>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Targeted_Country__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Country__c</fullName>
    <label>Targeted Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeted_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merchant_Special_Process__c/Merchant_Special_Process__c.object-meta.xml
<CustomObject>
    <description>This Object will allow to handle the Merchant special processes (N.M.O. Xboarder, Follow-up, Debit note and Exit).</description>
    <label>Merchant Special Process</label>
    <nameField>
        <displayFormat>MSP-{0000000000}</displayFormat>
        <label>Merchant Special Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Special Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Special_Process__c/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <formula>Merchant__r.BizDev__r.FirstName + &quot; &quot; + Merchant__r.BizDev__r.LastName</formula>
    <label>BizDev</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Special_Process__c/fields/BizDev_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>BizDev_for_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field created to enable adding BizDev as approver in the Debit Note end date Reached approval process.</description>
    <label>BizDev for Approval</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchant_Special_Processes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merchant_Special_Process__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Special_Process_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merchant_Special_Process__c/fields/Targeted_Country__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Targeted Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Merchant__c</field>
            <operation>equals</operation>
            <valueField>Targeted_Country__c.Merchant__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Targeted_Country__c</referenceTo>
    <relationshipLabel>Merchant Special Processes</relationshipLabel>
    <relationshipName>Merchant_Special_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mystery_Order__c/Mystery_Order__c.object-meta.xml
<CustomObject>
    <label>Mystery Order</label>
    <nameField>
        <displayFormat>MO-{0000000000}</displayFormat>
        <label>Mystery Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mystery Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mystery_Order__c/fields/Current_BizDev__c.field-meta.xml
<CustomField>
    <fullName>Current_BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mystery_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mystery_Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To do</fullName>
                <default>true</default>
                <label>To do</label>
            </value>
            <value>
                <fullName>Stand-by</fullName>
            </value>
            <value>
                <fullName>Order made</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Result Shared</fullName>
            </value>
            <value>
                <fullName>Check done</fullName>
            </value>
            <value>
                <fullName>Product sent back</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Archived for BM</fullName>
            </value>
            <value>
                <fullName>Abort MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NMO_Process__c/NMO_Process__c.object-meta.xml
<CustomObject>
    <description>This Object is meant to manage the N.M.O. dedicated process.</description>
    <label>Launching Phase</label>
    <nameField>
        <displayFormat>NP-{0000000000}</displayFormat>
        <label>N.M.O. Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Launching Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NMO_Process__c/fields/BizDevApproval__c.field-meta.xml
<CustomField>
    <fullName>BizDevApproval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>N_M_O_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMO_Process__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NMO_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/Onboarding_Process__c.object-meta.xml
<CustomObject>
    <description>This Object is meant to manage the Onboarding dedicated process.</description>
    <label>Onboarding Process</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>Onboarding Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Process__c/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <formula>Merchant__r.BizDev__r.FirstName + &apos; &apos; + Merchant__r.BizDev__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BizDev</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/fields/Merchant_BizDev__c.field-meta.xml
<CustomField>
    <fullName>Merchant_BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Onboarding_Processes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/Targeted_Country__c.object-meta.xml
<CustomObject>
    <description>This Object is a Junction Object between Account and Country.</description>
    <label>Targeted Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Targeted Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeted_Country__c/fields/NMO_Process__c.field-meta.xml
<CustomField>
    <fullName>NMO_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N.M.O. Process</label>
    <referenceTo>NMO_Process__c</referenceTo>
    <relationshipLabel>Targeted Countries</relationshipLabel>
    <relationshipName>Targeted_Countries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Recipient_email_sales__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_sales__c</fullName>
    <label>Recipient email sales</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/Team_Email__c.field-meta.xml
<CustomField>
    <fullName>Team_Email__c</fullName>
    <formula>CASE( Team__c , 
					 &apos;SSM Back Watch U.S.&apos;, &apos;sam@backmarket.com&apos;, 
					 &apos;SSM Back Watch E.U.&apos;, &apos;backwatch@backmarket.com&apos;,
					 &apos;SSM Selfcare E.U.&apos;, &apos;selfcare@backmarket.com&apos;,
      Email 					 
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Identification</fullName>
        <default>true</default>
        <label>Identification</label>
    </customValue>
    <customValue>
        <fullName>Not relevant</fullName>
    </customValue>
    <customValue>
        <fullName>First-contact</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Future partnership</fullName>
    </customValue>
    <customValue>
        <fullName>N.M.O.</fullName>
        <label>Launching Phase</label>
    </customValue>
    <customValue>
        <fullName>Run</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NMO_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Waiting Phase</fullName>
    </customValue>
    <customValue>
        <fullName>Phase 1</fullName>
    </customValue>
    <customValue>
        <fullName>Phase 2</fullName>
    </customValue>
    <customValue>
        <fullName>Phase 3</fullName>
    </customValue>
    <customValue>
        <fullName>N.M.O. 2</fullName>
        <label>LP 2</label>
    </customValue>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <masterLabel>N.M.O. Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Onboarding_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business &amp; Quality Prerequisites</fullName>
    </customValue>
    <customValue>
        <fullName>Go-Live Prerequisites</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Abandonned</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Quality Prerequisites</fullName>
        <isActive>false</isActive>
        <label>Quality Prerequisites</label>
    </customValue>
    <masterLabel>Onboarding Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Special_Process_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pre-Exit Phase</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing Notice Period</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>On Going</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Phase 1</fullName>
    </customValue>
    <customValue>
        <fullName>Phase 2</fullName>
    </customValue>
    <customValue>
        <fullName>Phase 3</fullName>
    </customValue>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Refused</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Special Process Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Targeted_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Targeted Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
/**
 * @description       : Account trigger handler tests
 * @author            : Martin Lezer
 * @group             : Tests
 * @last modified on  : 09-06-2022
 * @last modified by  : Martin Lezer
**/
@IsTest public class AccountTriggerHandlerTest {
    private static final Integer NB_ACCOUNTS = 2;

    @IsTest
    static void testBizDevChange(){
        TestFactory factory = new TestFactory();
        factory.insertAccounts(NB_ACCOUNTS)
                .insertAlertsBulk()
                .insertCasesBulk()
                .insertCountriesBulk()
                .insertMSPProcessesBulk()
                .insertMysteryOrdersBulk()
                .insertOnboardingProcessesBulk()
                .insertNMOProcessesBulk();
        User u = factory.getUser();
        insert u;

        Account[] accs = [SELECT Id FROM Account];

        Test.startTest();
        factory.updateBulk(TestFactory.RECORD_TYPE.Onboarding, 'Stage__c', 'Ongoing');

        for(Account acc : accs){
            acc.OwnerId = u.Id;
        }
        update accs;
        Test.stopTest();

        // check accounts
        Formula.recalculateFormulas(new List<User>{u});
        Set<String> recipientEmailSales = new Set<String>();
        for(Account acc : [SELECT Recipient_email_sales__c, Manager_Sales__c FROM Account WHERE Id IN :accs]){
            recipientEmailSales.add(acc.Recipient_email_sales__c);

            System.assertNotEquals(null, acc.Manager_Sales__c, 'Wrong manager related to account');
            System.assertEquals(u.ManagerId, acc.Manager_Sales__c, 'Wrong manager related to account');
            System.assertNotEquals(null, acc.Recipient_email_sales__c, 'Wrong recipient email related to account');
            System.assertEquals(u.Team_Email__c, acc.Recipient_email_sales__c, 'Wrong recipient email related to account');
        }

        // check related records
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Alert__c WHERE BizDev__c = :u.Id].size(), 'Alerts bizdev was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Onboarding_Process__c WHERE Merchant_BizDev__c = :u.Id].size(), 'Onboardings bizdev was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM NMO_Process__c WHERE BizDevApproval__c = :u.Id].size(), 'NMO processes bizdev was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Merchant_Special_Process__c WHERE BizDev_for_Approval__c = :u.Id].size(), 'Merchant Special processes bizdev was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Case WHERE Merchant_BizDev__c = :u.Id].size(), 'Cases bizdev was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Mystery_Order__c WHERE Current_BizDev__c = :u.Id].size(), 'Mystery orders bizdev was not updated.');
        System.assertEquals([SELECT Id FROM Targeted_Country__c].size(), [SELECT Id FROM Targeted_Country__c WHERE Recipient_email_sales__c IN :recipientEmailSales].size(), 'Targeted countries recipient email sales was not updated.');
    }

    @IsTest
    static void testBizDevBuybackChange(){
        TestFactory factory = new TestFactory(true);
        factory.insertAccounts(NB_ACCOUNTS)
                .insertAlertsBulk()
                .insertCasesBulk()
                .insertCountriesBulk()
                .insertMSPProcessesBulk()
                .insertMysteryOrdersBulk()
                .insertOnboardingProcessesBulk()
                .insertNMOProcessesBulk();
        User u = factory.getUser();
        insert u;

        Account[] accs = [SELECT Id FROM Account];

        Test.startTest();
        factory.updateBulk(TestFactory.RECORD_TYPE.Onboarding, 'Stage__c', 'Business & Quality Prerequisites');
        factory.updateBulk(TestFactory.RECORD_TYPE.Alert, 'Stage__c', 'Monitoring Period');

        for(Account acc : accs){
            acc.OwnerId = u.Id;
        }
        update accs;
        Test.stopTest();

        // check accounts
        Formula.recalculateFormulas(new List<User>{u});
        for(Account acc : [SELECT Recipient_email_buyback__c, Manager_Buyback__c FROM Account WHERE Id IN :accs]){
            System.assertNotEquals(null, acc.Manager_Buyback__c, 'Wrong manager related to account');
            System.assertEquals(u.ManagerId, acc.Manager_Buyback__c, 'Wrong manager related to account');
            System.assertNotEquals(null, acc.Recipient_email_buyback__c, 'Wrong recipient email related to account');
            System.assertEquals(u.Team_Email__c, acc.Recipient_email_buyback__c, 'Wrong recipient email related to account');
        }

        // check related records
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Alert__c WHERE BizDev_Buyback__c = :u.Id].size(), 'Alerts bizdev buyback was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Onboarding_Process__c WHERE Merchant_BizDev__c = :u.Id].size(), 'Onboardings bizdev buyback was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Merchant_Special_Process__c WHERE BizDev_for_Approval__c = :u.Id].size(), 'Merchant Special processes bizdev buyback was not updated.');
        System.assertEquals(TestFactory.LOAD_TEST_NUMBER * NB_ACCOUNTS, [SELECT Id FROM Case WHERE Merchant_BizDev__c = :u.Id].size(), 'Cases bizdev buyback was not updated.');
    }
}