force-app/main/default/objects/Account/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/BizDev_Buyback__c.field-meta.xml
<CustomField>
    <fullName>BizDev_Buyback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev Buyback</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager_Buyback__c.field-meta.xml
<CustomField>
    <fullName>Manager_Buyback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager - Buyback</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager_Sales__c.field-meta.xml
<CustomField>
    <fullName>Manager_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager - Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchants8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_onboarding_processes__c.field-meta.xml
<CustomField>
    <fullName>Number_of_onboarding_processes__c</fullName>
    <description>Count of the number of Onboarding Process Records related to the Merchant.</description>
    <label>Number of Ongoing Onboarding Processes</label>
    <summaryFilterItems>
        <field>Onboarding_Process__c.Abandonned__c</field>
        <operation>notEqual</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Onboarding_Process__c.Go_Live_granted__c</field>
        <operation>notEqual</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Onboarding_Process__c.Stage__c</field>
        <operation>notEqual</operation>
        <value>Failed,Completed,Abandonned</value>
    </summaryFilterItems>
    <summaryForeignKey>Onboarding_Process__c.Merchant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Ongoing_MSP__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Ongoing_MSP__c</fullName>
    <label>Number of Ongoing MSP</label>
    <summaryFilterItems>
        <field>Merchant_Special_Process__c.Stage__c</field>
        <operation>equals</operation>
        <value>Pre-Exit Phase, Ongoing Notice Period</value>
    </summaryFilterItems>
    <summaryForeignKey>Merchant_Special_Process__c.Merchant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Ongoing_NMO_processes__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Ongoing_NMO_processes__c</fullName>
    <label>Number of Ongoing Launching Phases</label>
    <summaryFilterItems>
        <field>NMO_Process__c.Unlimited_granted__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NMO_Process__c.NMO_Failed__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NMO_Process__c.NMO_Success__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NMO_Process__c.NMO_Success__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>NMO_Process__c.Stage__c</field>
        <operation>notEqual</operation>
        <value>Saved, Failed</value>
    </summaryFilterItems>
    <summaryForeignKey>NMO_Process__c.Merchant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ongoing_Alerts__c.field-meta.xml
<CustomField>
    <fullName>Ongoing_Alerts__c</fullName>
    <label>Ongoing Alerts</label>
    <summaryFilterItems>
        <field>Alert__c.Stage__c</field>
        <operation>equals</operation>
        <value>Monitoring Period, Last Chance, Not compliant</value>
    </summaryFilterItems>
    <summaryForeignKey>Alert__c.Business_Name__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recipient_email_sales__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_sales__c</fullName>
    <label>Recipient email sales</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/BizDev_Buyback__c.field-meta.xml
<CustomField>
    <fullName>BizDev_Buyback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BizDev Buyback</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Alerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Is_Buyback__c.field-meta.xml
<CustomField>
    <fullName>Is_Buyback__c</fullName>
    <formula>RecordType.DeveloperName = &apos;Monitoring_Period_Buyback&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Buyback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Merchant_BizDev__c.field-meta.xml
<CustomField>
    <fullName>Merchant_BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Filled by PB</inlineHelpText>
    <label>Merchant BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recipient_email_sales__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_sales__c</fullName>
    <label>Recipient email sales</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/BuyBack_Bill_Process.recordType-meta.xml
<RecordType>
    <fullName>BuyBack_Bill_Process</fullName>
    <active>true</active>
    <businessProcess>BuyBack Bill Process</businessProcess>
    <description>Use this form to kick off a BuyBack Bill Process</description>
    <label>BuyBack Bill Process V1</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/BuyBack_Bill_Process_V2.recordType-meta.xml
<RecordType>
    <fullName>BuyBack_Bill_Process_V2</fullName>
    <active>true</active>
    <businessProcess>BuyBack Bill Process V2</businessProcess>
    <label>BuyBack Bill Process V2</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Quality_Test.recordType-meta.xml
<RecordType>
    <fullName>Quality_Test</fullName>
    <active>true</active>
    <businessProcess>Standard Support Process</businessProcess>
    <description>Quality Test Correction</description>
    <label>Quality Test - Sales</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Quality_Test_Buyback.recordType-meta.xml
<RecordType>
    <fullName>Quality_Test_Buyback</fullName>
    <active>true</active>
    <businessProcess>Standard Support Process</businessProcess>
    <label>Quality Test - Buyback</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Quality_Test_Language_test.recordType-meta.xml
<RecordType>
    <fullName>Quality_Test_Language_test</fullName>
    <active>true</active>
    <businessProcess>Standard Support Process</businessProcess>
    <label>Quality Test - Language test</label>
</RecordType>

force-app/main/default/objects/Merchant_Special_Process__c/Merchant_Special_Process__c.object-meta.xml
<CustomObject>
    <description>This Object will allow to handle the Merchant special processes (N.M.O. Xboarder, Follow-up, Debit note and Exit).</description>
    <label>Merchant Special Process</label>
    <nameField>
        <displayFormat>MSP-{0000000000}</displayFormat>
        <label>Merchant Special Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Special Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Special_Process__c/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <formula>Merchant__r.BizDev__r.FirstName + &quot; &quot; + Merchant__r.BizDev__r.LastName</formula>
    <label>BizDev</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Special_Process__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <description>The Merchant the special process is applied to.</description>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Merchant Special Processes</relationshipLabel>
    <relationshipName>Merchant_Special_Processes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Merchant_Special_Process__c/recordTypes/Exit.recordType-meta.xml
<RecordType>
    <fullName>Exit</fullName>
    <active>true</active>
    <label>Exit</label>
</RecordType>

force-app/main/default/objects/Merchant_Special_Process__c/recordTypes/Exit_buyback.recordType-meta.xml
<RecordType>
    <fullName>Exit_buyback</fullName>
    <active>true</active>
    <label>Exit buyback</label>
</RecordType>

force-app/main/default/objects/Merchant_Special_Process__c/recordTypes/Exit_U_S.recordType-meta.xml
<RecordType>
    <fullName>Exit_U_S</fullName>
    <active>true</active>
    <label>Exit US</label>
</RecordType>

force-app/main/default/objects/NMO_Process__c/NMO_Process__c.object-meta.xml
<CustomObject>
    <description>This Object is meant to manage the N.M.O. dedicated process.</description>
    <label>Launching Phase</label>
    <nameField>
        <displayFormat>NP-{0000000000}</displayFormat>
        <label>N.M.O. Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Launching Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NMO_Process__c/fields/Is_Buyback__c.field-meta.xml
<CustomField>
    <fullName>Is_Buyback__c</fullName>
    <formula>RecordType.DeveloperName = &apos;NMO_E_U_buyback&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Buyback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NMO_Process__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NMO_Processes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/Onboarding_Process__c.object-meta.xml
<CustomObject>
    <description>This Object is meant to manage the Onboarding dedicated process.</description>
    <label>Onboarding Process</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>Onboarding Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Process__c/fields/BizDev__c.field-meta.xml
<CustomField>
    <fullName>BizDev__c</fullName>
    <formula>Merchant__r.BizDev__r.FirstName + &apos; &apos; + Merchant__r.BizDev__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BizDev</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/fields/Is_Buyback__c.field-meta.xml
<CustomField>
    <fullName>Is_Buyback__c</fullName>
    <formula>OR(RecordType.DeveloperName = &apos;U_S_Onboarding_Buyback&apos;,  RecordType.DeveloperName = &apos;E_U_Buyback&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Buyback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/fields/Manager_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Manager_for_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manager of the BizDev that will be used as approver for the onboarding approval process.</description>
    <label>Manager for Approval</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Onboarding_Processes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Onboardings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Onboarding_Process__c/fields/Merchant_BizDev__c.field-meta.xml
<CustomField>
    <fullName>Merchant_BizDev__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant BizDev</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Onboarding_Processes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/Targeted_Country__c.object-meta.xml
<CustomObject>
    <description>This Object is a Junction Object between Account and Country.</description>
    <label>Targeted Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Targeted Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeted_Country__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Targeted Countries</relationshipLabel>
    <relationshipName>Targeted_Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/NMO_Process__c.field-meta.xml
<CustomField>
    <fullName>NMO_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N.M.O. Process</label>
    <referenceTo>NMO_Process__c</referenceTo>
    <relationshipLabel>Targeted Countries</relationshipLabel>
    <relationshipName>Targeted_Countries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Recipient_email_buyback__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_buyback__c</fullName>
    <label>Recipient email buyback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Targeted_Country__c/fields/Recipient_email_sales__c.field-meta.xml
<CustomField>
    <fullName>Recipient_email_sales__c</fullName>
    <label>Recipient email sales</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/Team_Email__c.field-meta.xml
<CustomField>
    <fullName>Team_Email__c</fullName>
    <formula>CASE( Team__c , 
					 &apos;SSM Back Watch U.S.&apos;, &apos;sam@backmarket.com&apos;, 
					 &apos;SSM Back Watch E.U.&apos;, &apos;backwatch@backmarket.com&apos;,
					 &apos;SSM Selfcare E.U.&apos;, &apos;selfcare@backmarket.com&apos;,
      Email 					 
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Identification</fullName>
        <default>true</default>
        <label>Identification</label>
    </customValue>
    <customValue>
        <fullName>Not relevant</fullName>
    </customValue>
    <customValue>
        <fullName>First-contact</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Future partnership</fullName>
    </customValue>
    <customValue>
        <fullName>N.M.O.</fullName>
        <label>Launching Phase</label>
    </customValue>
    <customValue>
        <fullName>Run</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Account Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
 * @description       : Account trigger handler used to update accounts manager and related account records if the accounts bizdev is changed
 * @author            : Martin Lezer
 * @group             : TriggerHandler
 * @last modified on  : 09-12-2022
 * @last modified by  : Martin Lezer
**/
public class AccountTriggerHandler extends TriggerHandler{
    public override void beforeUpdate(List<SObject> triggerNew, Map<Id, SObject> triggerNewMap, List<SObject> triggerOld, Map<Id, SObject> triggerOldMap) {
        // bizdev changed: handling merchant manager and recipient email depending on new bizdev
        Set<Id> usersIds = new Set<Id>();
        List<Account> accountsToUpdate = new List<Account>();
        List<Account> accountsBuybackToUpdate = new List<Account>();
        for(Account acc : (List<Account>) triggerNew){
            if(acc.OwnerId != ((Map<Id, Account>) triggerOldMap).get(acc.Id).OwnerId){
                usersIds.add(acc.OwnerId);
                accountsToUpdate.add(acc);
            }
            if(acc.BizDev_Buyback__c != ((Map<Id, Account>) triggerOldMap).get(acc.Id).BizDev_Buyback__c){
                usersIds.add(acc.BizDev_Buyback__c);
                accountsBuybackToUpdate.add(acc);
            }
        }

        if(accountsToUpdate.isEmpty() == false || accountsBuybackToUpdate.isEmpty() == false){
            Map<Id, User> usersById = new Map<Id, User>([SELECT ManagerId, Team_Email__c FROM User WHERE Id IN :usersIds]);

            for(Account acc : accountsToUpdate){
                User bizdev = usersById.get(acc.OwnerId);
                acc.Manager_Sales__c = bizdev.ManagerId;
                acc.Recipient_email_sales__c = bizdev.Team_Email__c;
            }

            for(Account acc : accountsBuybackToUpdate){
                User bizdev = usersById.get(acc.BizDev_Buyback__c);
                acc.Manager_Buyback__c = bizdev.ManagerId;
                acc.Recipient_email_buyback__c = bizdev.Team_Email__c;
            }
        }
    }

    public override void afterUpdate(List<SObject> triggerNew, Map<Id, SObject> triggerNewMap, List<SObject> triggerOld, Map<Id, SObject> triggerOldMap) {
        //bizdev changed: updating related records bizdev and manager change
        //                onboarding processes
        //                NMO processes
        //                merchant special processes
        //                alerts
        //                mystery orders
        //                targeted countries
        LogService logs = new LogService(String.valueOf(this).substring(0,String.valueOf(this).indexOf(':'))); //sending current class name

        Map<Id, Account> oldAccounts = (Map<Id, Account>) triggerOldMap;
        Set<Id> accountsBizDevUpdated = new Set<Id>();
        Set<Id> onlyBizDevUpdatedAccount = new Set<Id>();
        Set<Id> accountsOnboardingToUpdate = new Set<Id>();
        Set<Id> accountsNMOToUpdate = new Set<Id>();
        Set<Id> accountsMSPToUpdate = new Set<Id>();
        Set<Id> accountsAlertsToUpdate = new Set<Id>();
        Set<Id> onlyBizDevBuybackUpdatedAccount = new Set<Id>();
        Set<Id> accountsOnboardingBuybackToUpdate = new Set<Id>();
        Set<Id> accountsMSPBuybackToUpdate = new Set<Id>();
        Set<Id> accountsAlertsBuybackToUpdate = new Set<Id>();
        for(Account acc : (List<Account>) triggerNew){
            if(acc.OwnerId != oldAccounts.get(acc.Id).OwnerId || acc.Manager_Sales__c != oldAccounts.get(acc.Id).Manager_Sales__c){
                accountsBizDevUpdated.add(acc.Id);

                // for cases, mystery orders and targeted countries we only need the bizdev to be updated (manager not needed)
                if(acc.OwnerId != oldAccounts.get(acc.Id).OwnerId){
                    onlyBizDevUpdatedAccount.add(acc.Id);
                }

                if(acc.Number_of_onboarding_processes__c > 0){
                    accountsOnboardingToUpdate.add(acc.Id);
                }
                if(acc.Number_of_Ongoing_NMO_processes__c > 0){
                    accountsNMOToUpdate.add(acc.Id);
                }
                if(acc.Number_of_Ongoing_MSP__c > 0){
                    accountsMSPToUpdate.add(acc.Id);
                }
                if(acc.Ongoing_Alerts__c > 0){
                    accountsAlertsToUpdate.add(acc.Id);
                }
            }
            // buyback update
            if(acc.BizDev_Buyback__c != oldAccounts.get(acc.Id).BizDev_Buyback__c || acc.Manager_Buyback__c != oldAccounts.get(acc.Id).Manager_Buyback__c){
                accountsBizDevUpdated.add(acc.Id);

                // for cases, mystery orders and targeted countries we only need the bizdev to be updated (manager not needed)
                if(acc.BizDev_Buyback__c != oldAccounts.get(acc.Id).BizDev_Buyback__c){
                    onlyBizDevBuybackUpdatedAccount.add(acc.Id);
                }

                if(acc.Number_of_onboarding_processes__c > 0){
                    accountsOnboardingBuybackToUpdate.add(acc.Id);
                }
                if(acc.Number_of_Ongoing_MSP__c > 0){
                    accountsMSPBuybackToUpdate.add(acc.Id);
                }
                if(acc.Ongoing_Alerts__c > 0){
                    accountsAlertsBuybackToUpdate.add(acc.Id);
                }
            }
        }

        if(accountsBizDevUpdated.isEmpty() == false){
            logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, accountsBizDevUpdated, 'Process started');

            Map<Id, Account> newAccounts = (Map<Id, Account>) triggerNewMap;
            List<SObject> recordsToUpdate = new List<SObject>();
            // onboarding processes
            if(accountsOnboardingToUpdate.isEmpty() == false || accountsOnboardingBuybackToUpdate.isEmpty() == false){
                Map<Id, Onboarding_Process__c> onboardingsToUpdate = new Map<Id, Onboarding_Process__c>([SELECT Merchant__c, Is_Buyback__c FROM Onboarding_Process__c 
                                                                                                         WHERE (Merchant__c IN :accountsOnboardingToUpdate OR Merchant__c IN :accountsOnboardingBuybackToUpdate)]);

                logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, onboardingsToUpdate.keySet(), 'Updating onboardings');

                for(Onboarding_Process__c onboarding : onboardingsToUpdate.values()){
                    if(accountsOnboardingToUpdate.contains(onboarding.Merchant__c) && onboarding.Is_Buyback__c == false){
                        onboarding.Manager_for_Approval__c = newAccounts.get(onboarding.Merchant__c).Manager_Sales__c;
                        onboarding.Merchant_BizDev__c = newAccounts.get(onboarding.Merchant__c).OwnerId;

                        recordsToUpdate.add(onboarding);
                    }else if(accountsOnboardingBuybackToUpdate.contains(onboarding.Merchant__c) && onboarding.Is_Buyback__c == true){
                        onboarding.Manager_for_Approval__c = newAccounts.get(onboarding.Merchant__c).Manager_Buyback__c;
                        onboarding.Merchant_BizDev__c = newAccounts.get(onboarding.Merchant__c).BizDev_Buyback__c;

                        recordsToUpdate.add(onboarding);
                    }
                }
            }
            // NMO processes
            if(accountsNMOToUpdate.isEmpty() == false){
                Map<Id, NMO_Process__c> NMOToUpdate = new Map<Id, NMO_Process__c>([SELECT Merchant__c FROM NMO_Process__c 
                                                                                   WHERE Merchant__c IN :accountsNMOToUpdate 
                                                                                         AND Stage__c != 'Saved' AND Stage__c != 'Failed' 
                                                                                         AND Is_Buyback__c = false]);

                logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, NMOToUpdate.keySet(), 'Updating NMO');

                for(NMO_Process__c nmo : NMOToUpdate.values()){
                    nmo.Manager__c = newAccounts.get(nmo.Merchant__c).Manager_Sales__c;
                    nmo.BizDevApproval__c = newAccounts.get(nmo.Merchant__c).OwnerId;

                    recordsToUpdate.add(nmo);
                }
            }
            // merchant special processes
            if(accountsMSPToUpdate.isEmpty() == false || accountsMSPBuybackToUpdate.isEmpty() == false){
                Id MSPRecordTypeExitId = Schema.SObjectType.Merchant_Special_Process__c.getRecordTypeInfosByDeveloperName().get('Exit').getRecordTypeId();
                Id MSPRecordTypeExitUSId = Schema.SObjectType.Merchant_Special_Process__c.getRecordTypeInfosByDeveloperName().get('Exit_U_S').getRecordTypeId();
                Id MSPRecordTypeExitBuybackId = Schema.SObjectType.Merchant_Special_Process__c.getRecordTypeInfosByDeveloperName().get('Exit_buyback').getRecordTypeId();
                Map<Id, Merchant_Special_Process__c> MSPToUpdate = new Map<Id, Merchant_Special_Process__c>([SELECT Merchant__c, RecordTypeId, Stage__c FROM Merchant_Special_Process__c 
                                                                                                             WHERE (Merchant__c IN :accountsMSPToUpdate OR Merchant__c IN :accountsMSPBuybackToUpdate) 
                                                                                                                   AND Stage__c != 'Done' AND Stage__c != 'Cancelled' 
                                                                                                                   AND (RecordTypeId = :MSPRecordTypeExitId OR RecordTypeId = :MSPRecordTypeExitUSId OR RecordTypeId = :MSPRecordTypeExitBuybackId)]);

                logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, MSPToUpdate.keySet(), 'Updating MSP');
                                                            
                for(Merchant_Special_Process__c msp : MSPToUpdate.values()){
                    if(accountsMSPToUpdate.contains(msp.Merchant__c) && (msp.RecordTypeId == MSPRecordTypeExitId || msp.RecordTypeId == MSPRecordTypeExitUSId)){
                        msp.Customer_Champion_Manager__c = newAccounts.get(msp.Merchant__c).Manager_Sales__c;
                        msp.BizDev_for_Approval__c = newAccounts.get(msp.Merchant__c).OwnerId;

                        recordsToUpdate.add(msp);
                    }else if(accountsMSPBuybackToUpdate.contains(msp.Merchant__c) && msp.RecordTypeId == MSPRecordTypeExitBuybackId){
                        msp.Customer_Champion_Manager__c = newAccounts.get(msp.Merchant__c).Manager_Buyback__c;
                        msp.BizDev_for_Approval__c = newAccounts.get(msp.Merchant__c).BizDev_Buyback__c;

                        recordsToUpdate.add(msp);
                    }
                }
            }
            // alerts
            if(accountsAlertsToUpdate.isEmpty() == false || accountsAlertsBuybackToUpdate.isEmpty() == false){
                Map<Id, Alert__c> alertsToUpdate = new Map<Id, Alert__c>([SELECT Business_Name__c, Is_Buyback__c, Stage__c FROM Alert__c 
                                                                          WHERE (Business_Name__c IN :accountsAlertsToUpdate OR Business_Name__c IN :accountsAlertsBuybackToUpdate)
                                                                                AND (Stage__c = 'Monitoring Period' OR Stage__c = 'Last chance' OR Stage__c = 'In progress' OR Stage__c = 'Not compliant')]);

                logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, alertsToUpdate.keySet(), 'Updating alerts');

                for(Alert__c alert : alertsToUpdate.values()){
                    if(accountsAlertsToUpdate.contains(alert.Business_Name__c) && alert.Is_Buyback__c == false){
                        alert.Manager__c = newAccounts.get(alert.Business_Name__c).Manager_Sales__c;
                        alert.BizDev__c = newAccounts.get(alert.Business_Name__c).OwnerId;
                        alert.Recipient_email_sales__c = newAccounts.get(alert.Business_Name__c).Recipient_email_sales__c;

                        recordsToUpdate.add(alert);
                    }else if(accountsAlertsBuybackToUpdate.contains(alert.Business_Name__c) && alert.Is_Buyback__c == true && (alert.Stage__c == 'Monitoring Period' || alert.Stage__c == 'Last chance')){
                        alert.Manager__c = newAccounts.get(alert.Business_Name__c).Manager_Buyback__c;
                        alert.BizDev_Buyback__c = newAccounts.get(alert.Business_Name__c).BizDev_Buyback__c;
                        alert.Recipient_email_sales__c = newAccounts.get(alert.Business_Name__c).Recipient_email_sales__c;
                        alert.Recipient_email_buyback__c = newAccounts.get(alert.Business_Name__c).Recipient_email_buyback__c;

                        recordsToUpdate.add(alert);
                    }
                }
            }

            if(onlyBizDevUpdatedAccount.isEmpty() == false || onlyBizDevBuybackUpdatedAccount.isEmpty() == false){
                // cases
                Id caseQualityTestRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Quality_Test').getRecordTypeId();
                Id caseLanguageTestRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Quality_Test_Language_test').getRecordTypeId();
                Id caseBuyBackBillProcessRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BuyBack_Bill_Process').getRecordTypeId();
                Id caseBuyBackBillProcess2RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BuyBack_Bill_Process_V2').getRecordTypeId();
                Id caseQualityTestBuyBackRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Quality_Test_Buyback').getRecordTypeId();

                Map<Id, Case> casesToUpdate = new Map<Id, Case>([SELECT AccountId, RecordTypeId FROM Case 
                                                                 WHERE (AccountId IN :onlyBizDevUpdatedAccount OR AccountId IN :onlyBizDevBuybackUpdatedAccount) 
                                                                       AND Stage__c = 'Draft' 
                                                                       AND (RecordTypeId = :caseQualityTestRecordTypeId OR RecordTypeId = :caseLanguageTestRecordTypeId
                                                                           OR RecordTypeId = :caseBuyBackBillProcessRecordTypeId OR RecordTypeId = :caseQualityTestBuyBackRecordTypeId OR RecordTypeId = :caseBuyBackBillProcess2RecordTypeId)]);
                
                logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, casesToUpdate.keySet(), 'Updating cases');

                for(Case c : casesToUpdate.values()){
                    if(onlyBizDevUpdatedAccount.contains(c.AccountId) && (c.RecordTypeId == caseQualityTestRecordTypeId || c.RecordTypeId == caseLanguageTestRecordTypeId)){
                        c.Merchant_BizDev__c = newAccounts.get(c.AccountId).OwnerId;
                        c.Recipient_email_sales__c = newAccounts.get(c.AccountId).Recipient_email_sales__c;

                        recordsToUpdate.add(c);
                    }else if(onlyBizDevBuybackUpdatedAccount.contains(c.AccountId) && (c.RecordTypeId == caseBuyBackBillProcessRecordTypeId || c.RecordTypeId == caseQualityTestBuyBackRecordTypeId || c.RecordTypeId == caseBuyBackBillProcess2RecordTypeId)){
                        c.Merchant_BizDev__c = newAccounts.get(c.AccountId).BizDev_Buyback__c;
                        c.Recipient_email_buyback__c = newAccounts.get(c.AccountId).Recipient_email_buyback__c;
                        c.OwnerId = newAccounts.get(c.AccountId).BizDev_Buyback__c;

                        recordsToUpdate.add(c);
                    }
                }

                if(onlyBizDevUpdatedAccount.isEmpty() == false){
                    // mystery orders
                    Map<Id, Mystery_Order__c> ordersToUpdate = new Map<Id, Mystery_Order__c>([SELECT Merchant_Name__c FROM Mystery_Order__c 
                                                                                              WHERE Merchant_Name__c IN :onlyBizDevUpdatedAccount 
                                                                                                    AND (Stage__c = 'To do' OR Stage__c = 'Stand-by' OR Stage__c = 'Order made' OR Stage__c = 'Received' OR Stage__c = 'Check done')]);
                    
                    logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, ordersToUpdate.keySet(), 'Updating mystery orders');
                    
                    for(Mystery_Order__c order : ordersToUpdate.values()){
                        order.Current_BizDev__c = newAccounts.get(order.Merchant_Name__c).OwnerId;

                        recordsToUpdate.add(order);
                    }
                    // targeted countries
                    Map<Id, Targeted_Country__c> countriesToUpdate = new Map<Id, Targeted_Country__c>([SELECT Merchant__c FROM Targeted_Country__c 
                                                                                                       WHERE Merchant__c IN :onlyBizDevUpdatedAccount]);

                    logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, countriesToUpdate.keySet(), 'Updating targeted countries');

                    for(Targeted_Country__c country : countriesToUpdate.values()){
                        country.Recipient_email_sales__c = newAccounts.get(country.Merchant__c).Recipient_email_sales__c;

                        recordsToUpdate.add(country);
                    }
                }
            }

            Map<Id, SObject> recordsToUpdateById = new Map<Id, SObject>(recordsToUpdate);
            if(recordsToUpdateById.isEmpty() == false){
                try{
                    logs.addLog(LogService.LOG_TYPE.INFO, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, recordsToUpdateById.keySet(), 'Update to database starting');

                    update recordsToUpdateById.values();

                    logs.addLog(LogService.LOG_TYPE.SUCCESS, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, recordsToUpdateById.keySet(), 'Update to database finished');
                }catch(DmlException e){
                    logs.addLog(LogService.LOG_TYPE.ERROR, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, recordsToUpdateById.keySet(), e.getMessage());
                }catch(Exception e){
                    logs.addLog(LogService.LOG_TYPE.ERROR, LogService.PROCESS.ACCOUNT_BIZDEV_CHANGED, recordsToUpdateById.keySet(), e.getMessage());
                }finally{
                    logs.publishLogs();
                }
            }
        }
    }
}