force-app/main/default/objects/User/fields/ByPassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassValidationRules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/ByPassWorkflow__c.field-meta.xml
<CustomField>
    <fullName>ByPassWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassWorkflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestHelp.cls
public class TestHelp {

    public static User createUser(){
        User u = new User(
                alias = 'standt',
                email='standarduser@testorg.com', 
                emailencodingkey='UTF-8',
                lastname='Testing',
                languagelocalekey='fr', 
                localesidkey='fr_FR',
                //profileId = Config__c.getValues('UserAdminProfile').Value__c,
                timezonesidkey='America/Los_Angeles',
                username=Math.random()+'test@testorg.com'
                //ByPassWorkflow__c = true,
                //ByPassValidationRules__c = true
            );
            return u;
        }
    
    public static User createCustomerChampionUser(){
        Id profileIdCustomerChampion = [Select Id From Profile Where Name='System Administrator'].Id;

        User u = new User(
                alias = 'standt',
                email='standarduser@testorg.com', 
                emailencodingkey='UTF-8',
                lastname='Testing',
                languagelocalekey='fr', 
                localesidkey='fr_FR',
                profileId = profileIdCustomerChampion,
                timezonesidkey='America/Los_Angeles',
                username=Math.random()+'test@testorg.com'
                //ByPassWorkflow__c = true,
                //ByPassValidationRules__c = true
            );
            return u;
        }
}